language: python
python:
  - "3.3"
  - "3.4"
install:
  - pip install flake8
  - pip install coveralls
script:
  - flake8 .
  - coverage run --branch --source data tests.py
after_success:
  - coveralls
